apiVersion: v1
kind: Secret
metadata:
  name: db-catalog-service-secret
  namespace: workshop
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_NAME: workshop-catalog-service
